# Generated by Django 4.0.6 on 2022-07-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploadImg', models.ImageField(default='property_post.jpg', upload_to='images/')),
            ],
        ),
    ]
